.TH README 1
.SH NAME
readme \- README reader
.SH SYNOPSIS
.B readme
.RB [ \-cep ]
.RI [ dir ]
.SH DESCRIPTION
.B readme
displays to the standard output the head of the first found README file in the
current directory or in a directory up in the directory hierarchy.
If a directory is given as argument, use it in place of the current directory.
.PP
The options are as follows:
.TP
.B \-c
Cat mode.
Rather than display only the head of the README file, displays it entirely.
.TP
.B \-e
Editor mode.
Edit the README file rather than displaying it.
.TP
.B \-p
Pager mode.
Display the README file in pager.
.PP
All options are mutually exclusive.
.SH ENVIRONMENT
The following environment variables affect the execution of
.B readme
.TP
.B EDITOR, VISUAL
Specifies an editor to use.
If both EDITOR and VISUAL are set, VISUAL takes precedence.
If neither EDITOR nor VISUAL are set, the default is vi(1).
.TP
.B PAGER
Specifies the pager to use.
If it is not set, use more(1).
